// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoKFN49s4MLNhrh_E2kfHetVL_aGHbxFc',
    appId: '1:944027543062:web:b00a6db57a432158e6b737',
    messagingSenderId: '944027543062',
    projectId: 'udhar-app-48d89',
    authDomain: 'udhar-app-48d89.firebaseapp.com',
    storageBucket: 'udhar-app-48d89.firebasestorage.app',
    measurementId: 'G-LYFWB6PQNP',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDBSrDqUWJTTvxEUxGMoDM37FneYTxM3w',
    appId: '1:944027543062:ios:6dd190a3486f4042e6b737',
    messagingSenderId: '944027543062',
    projectId: 'udhar-app-48d89',
    storageBucket: 'udhar-app-48d89.firebasestorage.app',
    iosBundleId: 'com.example.udharApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDBSrDqUWJTTvxEUxGMoDM37FneYTxM3w',
    appId: '1:944027543062:ios:6dd190a3486f4042e6b737',
    messagingSenderId: '944027543062',
    projectId: 'udhar-app-48d89',
    storageBucket: 'udhar-app-48d89.firebasestorage.app',
    iosBundleId: 'com.example.udharApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoKFN49s4MLNhrh_E2kfHetVL_aGHbxFc',
    appId: '1:944027543062:web:264b90b1cf61406ee6b737',
    messagingSenderId: '944027543062',
    projectId: 'udhar-app-48d89',
    authDomain: 'udhar-app-48d89.firebaseapp.com',
    storageBucket: 'udhar-app-48d89.firebasestorage.app',
    measurementId: 'G-F7DXWPFKZK',
  );
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAX3X1khhYUU0oCwk73SkFt6Kmfd8xTWtM',
    appId: '1:944027543062:android:c646ddcc44846e63e6b737',
    messagingSenderId: '944027543062',
    projectId: 'udhar-app-48d89',
    storageBucket: 'udhar-app-48d89.firebasestorage.app',
  );
}
